[package]
name = "odin"
version = "0.3.5"
edition = "2021"
license = "MIT"

[lib]
path = "src/odin.rs"
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
zed_extension_api = "0.7.0"
