name = "Odin"
grammar = "odin"
path_suffixes = ["odin"]
line_comments = ["// "]
block_comment = ["/* ", " */"]
autoclose_before = ";:.,=}])>"
hard_tabs = true
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "/*", end = "*/", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
]
debuggers = ["CodeLLDB"]
